---
- hosts: web1
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
      - name: Install apache
        yum:
          name:
            - update
            - httpd
            - php
            - php-mysqlnd
          state: present      